version: "3"

services:
  zookeeper:
    image: docker.io/bitnami/zookeeper:3.7
    hostname: zookeeper
    ports:
      - "3181:2181"
    volumes:
      - "zookeeper_data:/bitnami"
      - "./keys/truststore/kafka.truststore.jks:/opt/bitnami/zookeeper/config/certs/zookeeper.truststore.jks:ro"
      - "./keys/keystore/zookeeper.keystore.jks:/opt/bitnami/zookeeper/config/certs/zookeeper.keystore.jks:ro"
    environment:
      - ZOO_ENABLE_AUTH=yes
      - ZOO_SERVER_USERS=kafka
      - ZOO_SERVER_PASSWORDS=kafka_password
      - ZOO_CLIENT_USER=kafka
      - ZOO_CLIENT_PASSWORD=kafka_password
      
      - ZOO_TLS_CLIENT_ENABLE=true
      - ZOO_TLS_CLIENT_KEYSTORE_PASSWORD=test1234
      - ZOO_TLS_CLIENT_KEYSTORE_FILE=/opt/bitnami/zookeeper/config/certs/zookeeper.truststore.jks
      - ZOO_TLS_CLIENT_TRUSTSTORE_PASSWORD=test1234
      - ZOO_TLS_CLIENT_TRUSTSTORE_FILE=/opt/bitnami/zookeeper/config/certs/zookeeper.keystore.jks
      
  kafka-0:
    image: docker.io/bitnami/kafka:2
    hostname: kafka-0
    ports:
      - "9092:9092"
    volumes:
      - "./keys/truststore/kafka.truststore.jks:/opt/bitnami/kafka/config/certs/kafka.truststore.jks:ro"
      - "./keys/keystore/kafka-0.keystore.jks:/opt/bitnami/kafka/config/certs/kafka.keystore.jks:ro"
      - "./keys/truststore/kafka.truststore.jks:/opt/bitnami/kafka/config/certs/zookeeper.truststore.jks:ro"
      - "./keys/keystore/zookeeper.keystore.jks:/opt/bitnami/kafka/config/certs/zookeeper.keystore.jks:ro"
      - "kafka_0_data:/bitnami/kafka"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ZOOKEEPER_PROTOCOL=SASL
      - KAFKA_ZOOKEEPER_TLS_KEYSTORE_PASSWORD=test1234
      - KAFKA_ZOOKEEPER_TLS_TRUSTSTORE_PASSWORD=test1234
      - KAFKA_ZOOKEEPER_USER=kafka
      - KAFKA_ZOOKEEPER_PASSWORD=kafka_password
      - KAFKA_ZOOKEEPER_TLS_VERIFY_HOSTNAME=false
      
      
      - KAFKA_CFG_BROKER_ID=0
      
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:SSL,CLIENT:SASL_SSL
      - KAFKA_CFG_LISTENERS=INTERNAL://:9093,CLIENT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=INTERNAL://kafka:9093,CLIENT://localhost:9092
      - KAFKA_INTER_BROKER_LISTENER_NAME=INTERNAL
      
      - KAFKA_CERTIFICATE_PASSWORD=test1234
#      - KAFKA_CLIENT_USER=user
#      - KAFKA_CLIENT_PASSWORD=password
    depends_on:
      - zookeeper
      
  kafka_internal_client:
    image: docker.io/bitnami/kafka:2
    command: sleep infinity

volumes:
  zookeeper_data:
    driver: local
  kafka_0_data:
    driver: local
