version: "3"

services:
  zookeeper:
    image: docker.io/bitnami/zookeeper:3.7
    ports:
      - "2181:2181"
    volumes:
      - "zookeeper_data:/bitnami"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka-0:
    image: docker.io/bitnami/kafka:2
    hostname: kafka-0
    ports:
      - "9092:9092"
    volumes:
      - "./keys/truststore/kafka.truststore.jks:/opt/bitnami/kafka/config/certs/kafka.truststore.jks:ro"
      - "./keys/keystore/kafka-0.keystore.jks:/opt/bitnami/kafka/config/certs/kafka.keystore.jks:ro"
      - "kafka_0_data:/bitnami/kafka"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      
      - KAFKA_CFG_BROKER_ID=0
      
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:SSL,CLIENT:SASL_SSL
      - KAFKA_CFG_LISTENERS=INTERNAL://:9093,CLIENT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=INTERNAL://kafka:9093,CLIENT://localhost:9092
      - KAFKA_INTER_BROKER_LISTENER_NAME=INTERNAL
      
      - KAFKA_CERTIFICATE_PASSWORD=test1234
#      - KAFKA_CLIENT_USER=user
#      - KAFKA_CLIENT_PASSWORD=password
    depends_on:
      - zookeeper
      
  kafka_internal_client:
    image: docker.io/bitnami/kafka:2
    command: sleep infinity

volumes:
  zookeeper_data:
    driver: local
  kafka_0_data:
    driver: local
